version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "13000:3000"
    command: sh entrypoint.sh