/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServiceWorkerDemoImport } from './routes/service-worker-demo'
import { Route as HelloWorldImport } from './routes/hello-world'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ServiceWorkerDemoRoute = ServiceWorkerDemoImport.update({
  id: '/service-worker-demo',
  path: '/service-worker-demo',
  getParentRoute: () => rootRoute,
} as any)

const HelloWorldRoute = HelloWorldImport.update({
  id: '/hello-world',
  path: '/hello-world',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hello-world': {
      id: '/hello-world'
      path: '/hello-world'
      fullPath: '/hello-world'
      preLoaderRoute: typeof HelloWorldImport
      parentRoute: typeof rootRoute
    }
    '/service-worker-demo': {
      id: '/service-worker-demo'
      path: '/service-worker-demo'
      fullPath: '/service-worker-demo'
      preLoaderRoute: typeof ServiceWorkerDemoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hello-world': typeof HelloWorldRoute
  '/service-worker-demo': typeof ServiceWorkerDemoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello-world': typeof HelloWorldRoute
  '/service-worker-demo': typeof ServiceWorkerDemoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hello-world': typeof HelloWorldRoute
  '/service-worker-demo': typeof ServiceWorkerDemoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hello-world' | '/service-worker-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hello-world' | '/service-worker-demo'
  id: '__root__' | '/' | '/hello-world' | '/service-worker-demo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelloWorldRoute: typeof HelloWorldRoute
  ServiceWorkerDemoRoute: typeof ServiceWorkerDemoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelloWorldRoute: HelloWorldRoute,
  ServiceWorkerDemoRoute: ServiceWorkerDemoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hello-world",
        "/service-worker-demo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hello-world": {
      "filePath": "hello-world.tsx"
    },
    "/service-worker-demo": {
      "filePath": "service-worker-demo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
